/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.curso.insultos.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.curso.insultos.model.Insulto;
import com.curso.insultos.model.InsultoModel;
import com.curso.insultos.model.InsultoSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Insulto service. Represents a row in the &quot;Insultos_Insulto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link InsultoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InsultoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InsultoImpl
 * @see Insulto
 * @see InsultoModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class InsultoModelImpl extends BaseModelImpl<Insulto>
	implements InsultoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a insulto model instance should use the {@link Insulto} interface instead.
	 */
	public static final String TABLE_NAME = "Insultos_Insulto";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "insultoId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "texto", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("insultoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("texto", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table Insultos_Insulto (uuid_ VARCHAR(75) null,insultoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,texto VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Insultos_Insulto";
	public static final String ORDER_BY_JPQL = " ORDER BY insulto.texto ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Insultos_Insulto.texto ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.curso.insultos.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.curso.insultos.model.Insulto"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.curso.insultos.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.curso.insultos.model.Insulto"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.curso.insultos.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.curso.insultos.model.Insulto"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long TEXTO_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Insulto toModel(InsultoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Insulto model = new InsultoImpl();

		model.setUuid(soapModel.getUuid());
		model.setInsultoId(soapModel.getInsultoId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTexto(soapModel.getTexto());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Insulto> toModels(InsultoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Insulto> models = new ArrayList<Insulto>(soapModels.length);

		for (InsultoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.curso.insultos.service.util.ServiceProps.get(
				"lock.expiration.time.com.curso.insultos.model.Insulto"));

	public InsultoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _insultoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setInsultoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _insultoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Insulto.class;
	}

	@Override
	public String getModelClassName() {
		return Insulto.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("insultoId", getInsultoId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("texto", getTexto());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long insultoId = (Long)attributes.get("insultoId");

		if (insultoId != null) {
			setInsultoId(insultoId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String texto = (String)attributes.get("texto");

		if (texto != null) {
			setTexto(texto);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getInsultoId() {
		return _insultoId;
	}

	@Override
	public void setInsultoId(long insultoId) {
		_insultoId = insultoId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTexto() {
		if (_texto == null) {
			return "";
		}
		else {
			return _texto;
		}
	}

	@Override
	public void setTexto(String texto) {
		_columnBitmask = -1L;

		if (_originalTexto == null) {
			_originalTexto = _texto;
		}

		_texto = texto;
	}

	public String getOriginalTexto() {
		return GetterUtil.getString(_originalTexto);
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Insulto.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Insulto.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Insulto toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Insulto)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		InsultoImpl insultoImpl = new InsultoImpl();

		insultoImpl.setUuid(getUuid());
		insultoImpl.setInsultoId(getInsultoId());
		insultoImpl.setGroupId(getGroupId());
		insultoImpl.setCompanyId(getCompanyId());
		insultoImpl.setUserId(getUserId());
		insultoImpl.setUserName(getUserName());
		insultoImpl.setCreateDate(getCreateDate());
		insultoImpl.setModifiedDate(getModifiedDate());
		insultoImpl.setTexto(getTexto());

		insultoImpl.resetOriginalValues();

		return insultoImpl;
	}

	@Override
	public int compareTo(Insulto insulto) {
		int value = 0;

		value = getTexto().compareTo(insulto.getTexto());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Insulto)) {
			return false;
		}

		Insulto insulto = (Insulto)obj;

		long primaryKey = insulto.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		InsultoModelImpl insultoModelImpl = this;

		insultoModelImpl._originalUuid = insultoModelImpl._uuid;

		insultoModelImpl._originalGroupId = insultoModelImpl._groupId;

		insultoModelImpl._setOriginalGroupId = false;

		insultoModelImpl._originalCompanyId = insultoModelImpl._companyId;

		insultoModelImpl._setOriginalCompanyId = false;

		insultoModelImpl._setModifiedDate = false;

		insultoModelImpl._originalTexto = insultoModelImpl._texto;

		insultoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Insulto> toCacheModel() {
		InsultoCacheModel insultoCacheModel = new InsultoCacheModel();

		insultoCacheModel.uuid = getUuid();

		String uuid = insultoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			insultoCacheModel.uuid = null;
		}

		insultoCacheModel.insultoId = getInsultoId();

		insultoCacheModel.groupId = getGroupId();

		insultoCacheModel.companyId = getCompanyId();

		insultoCacheModel.userId = getUserId();

		insultoCacheModel.userName = getUserName();

		String userName = insultoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			insultoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			insultoCacheModel.createDate = createDate.getTime();
		}
		else {
			insultoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			insultoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			insultoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		insultoCacheModel.texto = getTexto();

		String texto = insultoCacheModel.texto;

		if ((texto != null) && (texto.length() == 0)) {
			insultoCacheModel.texto = null;
		}

		return insultoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", insultoId=");
		sb.append(getInsultoId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", texto=");
		sb.append(getTexto());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.curso.insultos.model.Insulto");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>insultoId</column-name><column-value><![CDATA[");
		sb.append(getInsultoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>texto</column-name><column-value><![CDATA[");
		sb.append(getTexto());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Insulto.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Insulto.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _insultoId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _texto;
	private String _originalTexto;
	private long _columnBitmask;
	private Insulto _escapedModel;
}