/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.curso.insultos.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Insulto service. Represents a row in the &quot;Insultos_Insulto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.curso.insultos.model.impl.InsultoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.curso.insultos.model.impl.InsultoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Insulto
 * @see com.curso.insultos.model.impl.InsultoImpl
 * @see com.curso.insultos.model.impl.InsultoModelImpl
 * @generated
 */
@ProviderType
public interface InsultoModel extends BaseModel<Insulto>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a insulto model instance should use the {@link Insulto} interface instead.
	 */

	/**
	 * Returns the primary key of this insulto.
	 *
	 * @return the primary key of this insulto
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this insulto.
	 *
	 * @param primaryKey the primary key of this insulto
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this insulto.
	 *
	 * @return the uuid of this insulto
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this insulto.
	 *
	 * @param uuid the uuid of this insulto
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the insulto ID of this insulto.
	 *
	 * @return the insulto ID of this insulto
	 */
	public long getInsultoId();

	/**
	 * Sets the insulto ID of this insulto.
	 *
	 * @param insultoId the insulto ID of this insulto
	 */
	public void setInsultoId(long insultoId);

	/**
	 * Returns the group ID of this insulto.
	 *
	 * @return the group ID of this insulto
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this insulto.
	 *
	 * @param groupId the group ID of this insulto
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this insulto.
	 *
	 * @return the company ID of this insulto
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this insulto.
	 *
	 * @param companyId the company ID of this insulto
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this insulto.
	 *
	 * @return the user ID of this insulto
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this insulto.
	 *
	 * @param userId the user ID of this insulto
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this insulto.
	 *
	 * @return the user uuid of this insulto
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this insulto.
	 *
	 * @param userUuid the user uuid of this insulto
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this insulto.
	 *
	 * @return the user name of this insulto
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this insulto.
	 *
	 * @param userName the user name of this insulto
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this insulto.
	 *
	 * @return the create date of this insulto
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this insulto.
	 *
	 * @param createDate the create date of this insulto
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this insulto.
	 *
	 * @return the modified date of this insulto
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this insulto.
	 *
	 * @param modifiedDate the modified date of this insulto
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the texto of this insulto.
	 *
	 * @return the texto of this insulto
	 */
	@AutoEscape
	public String getTexto();

	/**
	 * Sets the texto of this insulto.
	 *
	 * @param texto the texto of this insulto
	 */
	public void setTexto(String texto);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Insulto insulto);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Insulto> toCacheModel();

	@Override
	public Insulto toEscapedModel();

	@Override
	public Insulto toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}